services:
  tinydungeon:
    container_name: tinydungeon
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:3001"
    volumes:
      - ./data:/app/data
    restart: always
